# Generated by Django 3.1.7 on 2021-03-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realbeast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.CharField(max_length=200)),
            ],
        ),
    ]
