# Generated by Django 3.1.7 on 2021-03-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realbeast', '0003_auto_20210312_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
