# Generated by Django 3.1.7 on 2021-03-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realbeast', '0006_auto_20210317_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='caption',
            field=models.CharField(default='This is a product caption.', max_length=200),
            preserve_default=False,
        ),
    ]
