# Generated by Django 3.1.7 on 2021-03-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realbeast', '0007_product_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='card_no',
            field=models.CharField(default='undefined', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PaymentInfo',
        ),
    ]
